
    create table Amigos (
        id bigint generated by default as identity (start with 1),
        direccion varchar(255),
        primary key (id)
    )

    create table Condiciones (
        id bigint generated by default as identity (start with 1),
        condicion varchar(255),
        primary key (id)
    )

    create table Criticas (
        id bigint generated by default as identity (start with 1),
        nota integer not null,
        texto varchar(255),
        partido_id bigint,
        primary key (id)
    )

    create table Infracciones (
        id bigint generated by default as identity (start with 1),
        momento varchar(255),
        numero integer not null,
        primary key (id)
    )

    create table Inscripciones (
        id bigint generated by default as identity (start with 1),
        TipoDeInscripcion varchar(255),
        jugador_id bigint,
        condicion_id bigint,
        primary key (id)
    )

    create table Jugador (
        id bigint generated by default as identity (start with 1),
        edad integer not null,
        handicap integer not null,
        nombre varchar(255),
        primary key (id)
    )

    create table Jugador_Amigos (
        Jugador_id bigint not null,
        amigos_id bigint not null
    )

    create table Partidos (
        id bigint generated by default as identity (start with 1),
        fecha varbinary(255),
        horario varbinary(255),
        lugar varchar(255),
        primary key (id)
    )

    create table Partidos_Inscripciones (
        Partidos_id bigint not null,
        inscripciones_id bigint not null
    )

    alter table Criticas 
        add constraint FK_jndv8xpyanb721ivfevylredn 
        foreign key (partido_id) 
        references Partidos

    alter table Criticas 
        add constraint FK_fp1qcp32mevkp7jul2l8uyk6o 
        foreign key (id) 
        references Jugador

    alter table Infracciones 
        add constraint FK_ruiiyddtj758vpt0gk594n7jn 
        foreign key (id) 
        references Jugador

    alter table Inscripciones 
        add constraint FK_4rluraq5gtrdtd39xcdxlr2kr 
        foreign key (jugador_id) 
        references Jugador

    alter table Inscripciones 
        add constraint FK_4327ydo9b9jyparu4byfdib7d 
        foreign key (condicion_id) 
        references Condiciones

    alter table Jugador_Amigos 
        add constraint FK_6b8b2i6i43h4afkdbp3ait94o 
        foreign key (amigos_id) 
        references Amigos

    alter table Jugador_Amigos 
        add constraint FK_ds5tg2g42frtt1256tvaebhic 
        foreign key (Jugador_id) 
        references Jugador

    alter table Partidos_Inscripciones 
        add constraint FK_qb3qcy6rfcslei8oghn75uffc 
        foreign key (inscripciones_id) 
        references Inscripciones

    alter table Partidos_Inscripciones 
        add constraint FK_1pxr2emyqr684jfyuu91phrqa 
        foreign key (Partidos_id) 
        references Partidos
