
    create table ASDs (
        id bigint generated by default as identity (start with 1),
        num integer,
        primary key (id)
    )

    create table Jugador (
        edad integer generated by default as identity (start with 1),
        handicap integer not null,
        nombre varchar(255),
        promedio double not null,
        promedioUltimoPartido double not null,
        primary key (edad)
    )
