
    create table Amigos (
        id bigint generated by default as identity (start with 1),
        direccion varchar(255),
        primary key (id)
    )

    create table Condiciones (
        id bigint generated by default as identity (start with 1),
        condicion varchar(255),
        primary key (id)
    )

    create table Criticas (
        id bigint generated by default as identity (start with 1),
        nota integer not null,
        texto varchar(255),
        partido_id bigint,
        primary key (id)
    )

    create table Denegaciones (
        id bigint generated by default as identity (start with 1),
        fecha varbinary(255),
        motivo varchar(255),
        inscripcion_id bigint,
        primary key (id)
    )

    create table Formaciones (
        id bigint generated by default as identity (start with 1),
        primary key (id)
    )

    create table Formaciones_Inscripciones (
        Formaciones_id bigint not null,
        equipoB_id bigint not null,
        equipoA_id bigint not null
    )

    create table Infracciones (
        id bigint generated by default as identity (start with 1),
        momento varchar(255),
        numero integer not null,
        primary key (id)
    )

    create table Inscripciones (
        id bigint generated by default as identity (start with 1),
        TipoDeInscripcion varchar(255),
        jugador_id bigint,
        condicion_id bigint,
        primary key (id)
    )

    create table Jugador (
        id bigint generated by default as identity (start with 1),
        edad integer not null,
        handicap integer not null,
        nombre varchar(255),
        primary key (id)
    )

    create table Jugador_Amigos (
        Jugador_id bigint not null,
        amigos_id bigint not null
    )

    create table Partidos (
        id bigint generated by default as identity (start with 1),
        EstadoDelPartido varchar(255),
        fecha varbinary(255),
        horario varbinary(255),
        lugar varchar(255),
        primary key (id)
    )

    create table Partidos_Inscripciones (
        Partidos_id bigint not null,
        posiblesJugadores_id bigint not null,
        inscripciones_id bigint not null
    )

    alter table Criticas 
        add constraint FK_jndv8xpyanb721ivfevylredn 
        foreign key (partido_id) 
        references Partidos

    alter table Criticas 
        add constraint FK_fp1qcp32mevkp7jul2l8uyk6o 
        foreign key (id) 
        references Jugador

    alter table Denegaciones 
        add constraint FK_hsrxci1fhrsega9d2t9or62pe 
        foreign key (inscripcion_id) 
        references Inscripciones

    alter table Denegaciones 
        add constraint FK_14vvj8lc0793g4gvsftpgd7bs 
        foreign key (id) 
        references Partidos

    alter table Formaciones 
        add constraint FK_8mkkoi6lkxsv5edm9u5odl1n4 
        foreign key (id) 
        references Partidos

    alter table Formaciones_Inscripciones 
        add constraint FK_7curfmmw3rxrgbs20wi8ly1jq 
        foreign key (equipoB_id) 
        references Inscripciones

    alter table Formaciones_Inscripciones 
        add constraint FK_lbnwlymwrl8aaqw1pnr7pvmns 
        foreign key (Formaciones_id) 
        references Formaciones

    alter table Formaciones_Inscripciones 
        add constraint FK_fdedhx0ntt505wqc80yimrao2 
        foreign key (equipoA_id) 
        references Inscripciones

    alter table Infracciones 
        add constraint FK_ruiiyddtj758vpt0gk594n7jn 
        foreign key (id) 
        references Jugador

    alter table Inscripciones 
        add constraint FK_4rluraq5gtrdtd39xcdxlr2kr 
        foreign key (jugador_id) 
        references Jugador

    alter table Inscripciones 
        add constraint FK_4327ydo9b9jyparu4byfdib7d 
        foreign key (condicion_id) 
        references Condiciones

    alter table Jugador_Amigos 
        add constraint FK_6b8b2i6i43h4afkdbp3ait94o 
        foreign key (amigos_id) 
        references Amigos

    alter table Jugador_Amigos 
        add constraint FK_ds5tg2g42frtt1256tvaebhic 
        foreign key (Jugador_id) 
        references Jugador

    alter table Partidos_Inscripciones 
        add constraint FK_ri13a4fn2ck4dtbv6qbp55df0 
        foreign key (posiblesJugadores_id) 
        references Inscripciones

    alter table Partidos_Inscripciones 
        add constraint FK_1pxr2emyqr684jfyuu91phrqa 
        foreign key (Partidos_id) 
        references Partidos

    alter table Partidos_Inscripciones 
        add constraint FK_qb3qcy6rfcslei8oghn75uffc 
        foreign key (inscripciones_id) 
        references Inscripciones
